server:
  port: 7003
  servlet:
    context-path: /thread
eureka:
  client:
    service-url:
        defaultZone: http://localhost:5060/eureka/eureka
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://localhost:7070/eureka/eureka
spring:
  application:
    name: product-server
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 5Wy43g&mvI+u
    #type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  returnPageInfo: check

